server:
  port: ${PORT:************}
  forward-headers-strategy: native

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URI:**************}
  profiles:
    active: dev


database-name: ${DB_NAME:**************}


logging:
  file:
    name: logs

api:
  module-name: PayKit
  version: 1.0
  url-domain: ${APP_URL_DOMAIN:http://localhost:${server.port}${server.servlet.context-path}}
  basepath: /api/v1
  basepath-admin: ${api.basepath}/admin
