server:
  port: ${PORT:************}
  forward-headers-strategy: native

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URI:**************}
  profiles:
    active: dev


database-name: ${DB_NAME:**************}


logging:
  file:
    name: logs

api:
  module-name: PayKit
  version: 1.0

  jwt:
    authorities:
      key: roles
    token:
      secret-key: ${JWT_SECRET:1xvrtrt56}
      expire-length: ${JWT_EXPIRE_LENGTH:86400000}